//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MatroskaCDL.rc
//
#define RESOURCE_VERSION_MAJOR 2
#define RESOURCE_VERSION_MINOR 8
#define IDD_CFGDIALOG                   101
#define IDD_TREEDIALOG                  102
#define IDD_DIALOG1                     104
#define IDD_DIALOG2                     105
#define IDD_DIALOG_ABOUT                105
#define IDD_PROPPAGE                    106
#define IDB_BITMAP1                     106
#define IDD_TAG_TAB                     107
#define IDD_TAG_SIMPLE_TAB              108
#define IDB_BITMAP_LOGO                 110
#define IDD_DIALOG_ADDTAG               115
#define IDD_DIALOG_DISPLAY_SIZE         117
#define IDD_DIALOG_DISPLAY_TEXT         118
#define IDI_ICON_WRENCH                 120
#define IDI_ICON_MKV1                   122
#define IDD_DIALOG_SHELL_OPTIONS        125
#define IDD_PROPPAGE_ATTACHMENT         126
#define IDI_ICON_MKV_BLUE               130
#define IDR_MENU_CLIPBOARD              131
#define IDI_ICON_MONKEY                 133
#define IDD_DIALOG_PROGRESS             135
#define IDD_DIALOG_MUXER                136
#define IDD_DIALOG_ICONS                137
#define IDR_PNG_MATROSKA_CDL            140
#define IDR_PNG_MATROSKA_INFO           142
#define IDD_DIALOG_SELECT_LANGUAGE      144
#define IDI_ICON_MKV6                   146
#define IDI_ICON_MKV_DOLL_4             147
#define IDD_DIALOG_CRASH                148
#define IDI_ICON_MKV_DOLL_5             148
#define IDI_ICON_AUDIO                  149
#define IDI_ICON_SUBTITLE               150
#define IDI_ICON_VIDEO                  151
#define IDI_ICON_COW                    152
#define IDD_DIALOG_ADD_SIMPLE_TAG       154
#define IDD_DIALOG_BITRATE              155
#define IDD_DIALOG_ADD_UID              156
#define IDD_PROPPAGE_CHAPTER            157
#define IDR_MP31                        158
#define IDI_ICON1                       159
#define IDI_ICON_SETUP                  159
#define IDC_EDIT_TITLE                  1001
#define IDC_LIST_TAGS                   1003
#define IDC_BUTTON_SAVE                 1004
#define IDC_EDIT_SELECTED_TAG_TEXT      1005
#define IDC_EDIT_SELECTED_TAG_TYPE      1006
#define IDC_LIST_TRACKS                 1009
#define IDC_STATIC_TRACK_UID            1010
#define IDC_STATIC_TRACK_NUMBER         1011
#define IDC_STATIC_TRACK_TYPE           1012
#define IDC_STATIC_TRACK_INFO           1013
#define IDC_COMBO_TAG_TYPE              1016
#define IDC_CHECK_DAR                   1017
#define IDC_CHECK_TAG_TAB               1018
#define IDC_COMBO1                      1019
#define IDC_CHECK_TAG_TAB_SIMPLE        1019
#define IDC_COMBO_TAG_SIMPLE_TRACKS     1019
#define IDC_COMBO_PROP_CHANGE           1019
#define IDC_COMBO_LANGUAGE_SELECTION    1019
#define IDC_COMBO_CONFIG_LANGUAGE       1019
#define IDC_COMBO_TAG_NAME              1019
#define IDC_COMBO_TAG_FIELD             1020
#define IDC_EDIT1                       1021
#define IDC_EDIT_TAG_TITLE              1021
#define IDC_EDIT_CACHE_LIMIT            1021
#define IDC_EDIT_CRASH_REPORT           1021
#define IDC_EDIT_TAG_VALUE              1021
#define IDC_EDIT_BITRATE_DISPLAY        1021
#define IDC_EDIT_ADD_UID                1021
#define IDC_EDIT_TAG_ALBUM              1022
#define IDC_EDIT_TAG_ARTIST             1023
#define IDC_COMBO_TAG_TRACKS            1024
#define IDC_STATIC_TAG_NAME             1025
#define IDC_EDIT_TAG_YEAR               1025
#define IDC_BUTTON_ADDTAG               1026
#define IDC_EDIT_TAG_BPM                1026
#define IDC_LIST_ADDTAG                 1027
#define IDC_EDIT_TAG_TRACKNO            1027
#define IDC_BUTTON_DELETETAG            1027
#define IDC_BUTTON_ADDTAG_CANCEL        1028
#define IDC_BUTTON_ADDTAG_OK            1029
#define IDC_STATIC_TAGADD_INFO          1030
#define IDC_STATIC_ABOUT                1031
#define IDC_BUTTON_PROP_ABOUT           1033
#define IDC_BUTTON_TAGS_RELOAD          1035
#define IDC_STATIC_ATTACHMENTS_LIST     1037
#define IDC_BUTTON_VIEW_ATTACHMENT      1038
#define IDC_STATIC_ATTACHMENT_INFO      1039
#define IDC_COMBO_ATTACHMENT            1040
#define IDC_STATIC_ATTACHMENT_FRAME     1041
#define IDC_BUTTON_CHANGE_DISPLAY_SIZE  1042
#define IDC_BUTTON_PROP_CHANGE          1042
#define IDC_BUTTON_LOAD_ATTACHMENTS     1043
#define IDC_EDIT_HEIGHT                 1044
#define IDC_EDIT_WIDTH                  1045
#define IDC_BUTTON_DISPLAY_SIZE_OK      1046
#define IDC_BUTTON_DISPLAY_SIZE_CANCEL  1047
#define IDC_RADIO_BASIC_INFOMATION      1048
#define IDC_RADIO_ADVANCED_INFO         1049
#define IDC_LIST_INFOMATION             1050
#define IDC_EDIT_ATTACHED_TEXT          1051
#define IDC_CHECK_ENABLE_TOOLTIPS       1052
#define IDC_CHECK_ENABLE_THUMBNAILS     1053
#define IDC_LIST_THUMBNAIL_ORDER        1058
#define IDC_SPIN_THUMBNAIL_ORDER        1061
#define IDC_COMBO_THUMBNAIL_RESIZE      1062
#define IDC_CHECK_DISPLAY_INFO          1065
#define IDC_CHECK_DISPLAY_TAG           1066
#define IDC_BUTTON_CONFIG               1066
#define IDC_CHECK_DISPLAY_ATTACHMENTS   1067
#define IDC_LIST_ATTACHMENT             1067
#define IDC_PROGRESS_BAR                1069
#define IDC_BUTTON_ABORT                1070
#define IDC_STATIC_PROGRESS             1071
#define IDC_CHECK_USE_SHORT_TOOLTIPS    1072
#define IDC_SPIN_FRAMETIME              1074
#define IDC_EDIT_FRAMETIME              1075
#define IDC_SPIN_DISPLAY_HEIGHT         1076
#define IDC_EDIT_THUMBNAIL_TIMEOUT      1076
#define IDC_SPIN_DISPLAY_WIDTH          1077
#define IDC_SPIN_FRAMETIME2             1077
#define IDC_PROGRESS_MUXING             1078
#define IDC_STATIC_MUXING               1079
#define IDC_BUTTON_CANCEL_MUXING        1080
#define IDC_RADIO_NO_ICON               1081
#define IDC_RADIO_MKV_JORY              1082
#define IDC_RADIO_MONKEY                1083
#define IDC_RADIO_MKV_BLUE              1084
#define IDC_BUTTON_SELECT_ICON          1085
#define IDC_CHECK_ENABLE_CONTEXT_MENU   1086
#define IDC_CHECK_ENABLE_TASK_THUMBNAILS 1087
#define IDC_CONFIG_OK                   1088
#define IDC_CONFIG_CANCEL               1089
#define IDC_REG_FILENAME                1090
#define IDC_TAG_DATETIMEPICKER_TIME     1091
#define IDC_STATIC_TAG_FOUND            1092
#define IDC_TAG_DATETIMEPICKER_DATE     1093
#define IDC_CHECK_ENABLE_DSHOW_FALLBACK 1095
#define IDC_CHECK_ENABLE_IMEDIADET_DSHOW_FALLBACK 1096
#define IDC_CHECK_ENABLE_COLUMN         1097
#define IDC_EDIT_ATTACHMENT             1098
#define IDC_SAVE_ATTACHMENT             1099
#define IDC_COMBO_TAG_GENRE             1104
#define IDC_EDIT_TAG_RATING             1106
#define IDC_EDIT_TAG_COMMENT            1107
#define IDC_SPIN_TAG_RATING             1108
#define IDC_SPIN_TAG_BPM                1109
#define IDC_BUTTON_SIMPLE_TAG_SAVE      1110
#define IDC_BUTTON_EXPORT_XML           1111
#define IDC_STATIC_ABOUT_IMAGE          1112
#define IDC_BUTTON_LANGUAGE_OK          1114
#define IDC_BUTTON_LANGUAGE_CANCEL      1115
#define IDC_BUTTON_CHOOSE_ICON          1116
#define IDC_SPIN_CACHE_LIMIT            1117
#define IDC_BUTTON_TAG_IMPORT           1118
#define IDC_LIST_VIEW_TRACKS            1119
#define IDC_BUTTON_SAVE_DUMP            1120
#define IDC_STATIC_CRASH_TITLE          1121
#define IDC_EDIT_CRASH_USER_TEXT        1123
#define IDC_BUTTON_CRASH_ME             1124
#define IDC_STATIC_ADD_TAG_1            1125
#define IDC_STATIC_DISPLAY_SIZE_1       1126
#define IDC_STATIC_DISPLAY_SIZE_2       1127
#define IDC_STATIC_DISPLAY_SIZE_3       1128
#define IDC_STATIC_LANGUAGE_1           1129
#define IDC_STATIC_CONFIG_1             1130
#define IDC_STATIC_CONFIG_2             1131
#define IDC_STATIC_CONFIG_4             1132
#define IDC_STATIC_CONFIG_3             1133
#define IDC_STATIC_CONFIG_10            1134
#define IDC_STATIC_CONFIG_6             1135
#define IDC_STATIC_CONFIG_7             1136
#define IDC_STATIC_CONFIG_9             1137
#define IDC_STATIC_CONFIG_8             1138
#define IDC_STATIC_CONFIG_5             1139
#define IDC_STATIC_CONFIG_11            1140
#define IDC_BUTTON_ABOUT_OK             1141
#define IDC_BUTTON_CONFIG_SET_TRANSLATION 1142
#define IDC_STATIC_PROGRESS_TITLE       1143
#define IDC_STATIC_ATTACHMENT_BORDER    1144
#define IDC_STATIC_ATTACHMENT_PREVIEW   1145
#define IDC_STATIC_INFO_BORDER          1146
#define IDC_STATIC_INFO_TRACK_BORDER    1147
#define IDC_STATIC_INFO_TRACKS          1148
#define IDC_STATIC_TAG_1                1149
#define IDC_STATIC_TAG_2                1150
#define IDC_STATIC_TAG_3                1151
#define IDC_STATIC_TAG_4                1152
#define IDC_STATIC_TAG_FRAME_BORDER     1153
#define IDC_STATIC_TAG_5                1154
#define IDC_LIST_VIEW_ICON_CHOICE       1155
#define IDC_STATIC_TRANSLATION_BY       1156
#define IDC_CHECK_ENABLE_CRASH_CATCHER  1158
#define IDC_BUTTON_ADD_SIMPLE_TAG_OK    1159
#define IDC_BUTTON_ADD_SIMPLE_TAG_CANCEL 1160
#define IDC_STATIC_NAME                 1161
#define IDC_STATIC_VALUE                1162
#define IDC_BUTTON_BITRATE              1163
#define IDC_BUTTON_BITRATE_OK           1165
#define IDC_STATIC_BITRATE_USAGE        1166
#define IDC_PROGRESS_BAR_BITRATE        1167
#define IDC_CHECK_AUTO_RELOAD_TAGS      1168
#define IDC_TAB_CONFIG                  1169
#define IDC_LIST_TAG_ASSIGNED_UID       1170
#define IDC_BUTTON_TAG_UID_ADD          1171
#define IDC_BUTTON_TAG_UID_DELETE       1172
#define IDC_LIST_TAG_ENTRIES            1173
#define IDC_BUTTON_TAG_ENTRY_ADD        1174
#define IDC_STATIC_TAG_ASSIGNED_UID     1175
#define IDC_BUTTON_TAG_ENTRY_DELETE     1176
#define IDC_BUTTON_ADD_UID_OK           1176
#define IDC_STATIC_TAG_ENTRIES          1177
#define IDC_BUTTON_ADD_UID_CANCEL       1177
#define IDC_STATIC_ADD_UID_1            1178
#define IDC_LIST_ADD_UID                1179
#define IDC_STATIC_CHAPTER_BORDER       1180
#define IDC_TREE_CHAPTER                1181
#define IDC_BUTTON1                     1182
#define IDC_BUTTON_ABOUT_LISTEN         1182
#define IDC_BUTTON_BITRATE_SAVE         1182
#define IDC_BUTTON_EXPORT_CHAPTERS_XML  1182
#define RESOURCE_VERSION_BUILD 2219
#define IDC_MENU_COPY_CLIPBOARD         40001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1183
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
